---
title: "Dataset Descriptions"
description:  |
  Brief descriptions of potential datasets and directions for research.
authors: "Cat Mahoney, Xiaolong Zhou"
date: "2025-03-03"
draft: FALSE
---

## MA Air Quality: EPA Dataset
Particulate matter, especially fine particles (PM2.5) can adversely affect human health. Specifically, these particles can irritate airways, decrease lung function, aggravate asthma, and lead to pulmonary issues like heart attacks [EPA](https://www.epa.gov/pm-pollution/health-and-environmental-effects-particulate-matter-pm).

[Download HERE!](https://www.epa.gov/outdoor-air-quality-data/download-daily-data) 
This data set shows daily measures of various air pollutants across the United States. We hope to focus on particulate matter exposure in neighborhoods around Boston, filtering data before downloading as follows:

* Pollutant: PM2.5
* Year: 2020
* Location: MA - Suffolk County

This will provide us with data from three sites: Kenmore Sq., Roxbury, and Dorchester. We would then compare particulate matter (PM) across 2020 census data to explore potential trends in pollutant exposure by race near Boston. We hypothesize that lower income communities that are more industrialized may have greater risk of PM exposure.

## Nutrition, Physical Activity, and Obesity - Behavioral Risk Factor Surveillance System
[Download HERE!](https://chronicdata.cdc.gov/Nutrition-Physical-Activity-and-Obesity/Nutrition-Physical-Activity-and-Obesity-Behavioral/hn4x-zwk7/data_preview) 
This dataset includes data on adult's diet, physical activity, and weight status from Behavioral Risk Factor Surveillance System. We can focus on nutrition and obesity in MA. We can filter the data by: 

* Year: 2022
* Data_value_type: Value
* LocationAbbr: MA

We will see several lines of data related to topics such as eating habits and weight indicators (obesity, overweight), which reflect the value of a certain nutrition or weight indicator in Massachusetts in 2022, and the corresponding confidence intervals, stratified categories, and so on. Further aggregating or visualizing these data will help us understand the nutrition and obesity status of Massachusetts adults in 2022. 

## U.S. Deaths by Suicide: CDC Dataset
According to the CDC, suicide is among the leading causes of death in the US, with rates steadily rising since 2000. Data also shows distinct demographic trends in suicide rates based on both race and gender.

The following dataset shows death rates by suicide by sex, race, Hispanic origin, and age from 1950 to 2022. We hope to identify longer term demographic trends in these data, and perhaps find time series economic or other datasets to identify potential drivers in changing rates of death by suicide over the years.

[Download HERE](https://catalog.data.gov/dataset/death-rates-for-suicide-by-sex-race-hispanic-origin-and-age-united-states-020c1)
