{
  "hash": "3ada32944bfe16040918bdf400440c94",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Blog 3: Backgrond and Data Analysis(summary, barplots, tables) \"\ndescription:  |\n  Preliminary Data Analysis, data background, and barplots for continuous variable, and tables for discrete variables.\nauthors: \"Background: Cat Mahoney, Yana Pathak. Data Analysis: Jiaxuan Li, Girish Hrithik Shivnauth, Xiaolong Zhou\"\ndate: \"2025-03-24\"\ndraft: FALSE\n---\n\n\n\n## Data Background\nThe EPA AirData project tracks air quality in the US, collecting data on pollutants that are linked to serious health risks. Specifically PM2.5 particles. These small particles, primarily from fossil fuel combustion and atmospheric chemical reactions, are known to impair lung function and increase cancer risks.\nThe 2024 study in Nature Communications (https://www.nature.com/articles/s41467-023-43492-9), showed in class, analyzed US air pollution trends from 1970 to 2010, showing that there were reductions in pollution due to efforts like the Clean Air Act. It also showed disparities, specifically how pollutant exposure varies by socioeconomic factors, as some communities experience slower improvements. \nOur study examines Boston’s PM2.5 levels using data from Roxbury, Kenmore Square, and Dorchester to focus on local trends. We are extending the timeline to the present, as we aim to identify emerging disparities and evaluate the continued effectiveness of air quality regulations.\n\n## Data Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)  \nlibrary(dplyr) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nepa_data <- readRDS(\"dataset/air_qual_clean.rds\")\n\nprint(dim(epa_data))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1694   10\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(names(epa_data))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Date\"                           \"Daily Mean PM2.5 Concentration\"\n [3] \"Daily AQI Value\"                \"Units\"                         \n [5] \"Local Site Name\"                \"Method Code\"                   \n [7] \"Method Description\"             \"County\"                        \n [9] \"Site Latitude\"                  \"Site Longitude\"                \n```\n\n\n:::\n\n```{.r .cell-code}\n### --- PM2.5 Concentration ---\npm25_stats <- summary(epa_data$`Daily Mean PM2.5 Concentration`)\nprint(pm25_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n -0.500   4.600   6.300   6.802   8.500  26.000 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean_pm25 <- mean(epa_data$`Daily Mean PM2.5 Concentration`, na.rm = TRUE)\nmedian_pm25 <- median(epa_data$`Daily Mean PM2.5 Concentration`, na.rm = TRUE)\nsd_pm25 <- sd(epa_data$`Daily Mean PM2.5 Concentration`, na.rm = TRUE)\nmin_pm25 <- min(epa_data$`Daily Mean PM2.5 Concentration`, na.rm = TRUE)\nmax_pm25 <- max(epa_data$`Daily Mean PM2.5 Concentration`, na.rm = TRUE)\niqr_pm25 <- IQR(epa_data$`Daily Mean PM2.5 Concentration`, na.rm = TRUE)\n\ncat(\"\\n--- PM2.5 Summary ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- PM2.5 Summary ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean PM2.5:\", mean_pm25, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean PM2.5: 6.801712 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median PM2.5:\", median_pm25, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian PM2.5: 6.3 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard Deviation:\", sd_pm25, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard Deviation: 3.264045 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Min:\", min_pm25, \"  Max:\", max_pm25, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMin: -0.5   Max: 26 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IQR:\", iqr_pm25, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIQR: 3.9 \n```\n\n\n:::\n\n```{.r .cell-code}\n### --- Site Latitude ---\nlat_stats <- summary(epa_data$`Site Latitude`)\nprint(lat_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  42.33   42.33   42.33   42.33   42.35   42.35 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean_lat <- mean(epa_data$`Site Latitude`, na.rm = TRUE)\nmedian_lat <- median(epa_data$`Site Latitude`, na.rm = TRUE)\nsd_lat <- sd(epa_data$`Site Latitude`, na.rm = TRUE)\nmin_lat <- min(epa_data$`Site Latitude`, na.rm = TRUE)\nmax_lat <- max(epa_data$`Site Latitude`, na.rm = TRUE)\niqr_lat <- IQR(epa_data$`Site Latitude`, na.rm = TRUE)\n\ncat(\"\\n--- Latitude Summary ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Latitude Summary ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean Latitude:\", mean_lat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Latitude: 42.33273 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median Latitude:\", median_lat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian Latitude: 42.3295 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard Deviation:\", sd_lat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard Deviation: 0.00993418 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Min:\", min_lat, \"  Max:\", max_lat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMin: 42.32519   Max: 42.34887 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IQR:\", iqr_lat, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIQR: 0.02368671 \n```\n\n\n:::\n\n```{.r .cell-code}\n### --- Site Longitude ---\nlon_stats <- summary(epa_data$`Site Longitude`)\nprint(lon_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n -71.10  -71.10  -71.08  -71.07  -71.06  -71.06 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean_lon <- mean(epa_data$`Site Longitude`, na.rm = TRUE)\nmedian_lon <- median(epa_data$`Site Longitude`, na.rm = TRUE)\nsd_lon <- sd(epa_data$`Site Longitude`, na.rm = TRUE)\nmin_lon <- min(epa_data$`Site Longitude`, na.rm = TRUE)\nmax_lon <- max(epa_data$`Site Longitude`, na.rm = TRUE)\niqr_lon <- IQR(epa_data$`Site Longitude`, na.rm = TRUE)\n\ncat(\"\\n--- Longitude Summary ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Longitude Summary ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean Longitude:\", mean_lon, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Longitude: -71.07442 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Median Longitude:\", median_lon, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian Longitude: -71.0826 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standard Deviation:\", sd_lon, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard Deviation: 0.01762767 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Min:\", min_lon, \"  Max:\", max_lon, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMin: -71.09716   Max: -71.05606 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IQR:\", iqr_lon, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIQR: 0.04110179 \n```\n\n\n:::\n:::\n\n\n\nDaily Mean PM2.5 Concentration\nThe Daily Mean PM2.5 Concentration is a key indicator of air quality. Based on our data, the average concentration is 6.801712 μg/m³, with a median of 6.3 μg/m³. The values range from 42.33 to 42.35, and the standard deviation is 3.264045. The interquartile range (IQR) is 3.9, showing the spread of the middle 50% of the data. \n\nThe Site Latitude\nThe Site Latitude values describe the north-south positioning of the air quality monitoring sites. The latitudes range from -71.10 to -71.06, with a mean of -42.33273 and median of 42.3295. This indicates that the stations are located across a wide vertical geographical spread.The standard deviation is 0.02368671, and the IQR is 0.02368671, suggesting varying coverage in the north-south direction.\n\nThe Site Longitude\nThe Site Longitude captures the east-west geographic spread of monitoring sites. The mean longitude is -71.07442, median is -71.0826, and the values range from -71.09716 to -71.05606. The standard deviation is 0.01762767. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)  \nlibrary(dplyr) \nlibrary(ggplot2)  \nepa_data <- readRDS(\"dataset/air_qual_clean.rds\")\n# 1. Scatter plot of PM2.5 vs AQI value\nggplot(epa_data, aes(x = `Daily Mean PM2.5 Concentration`, y = `Daily AQI Value`)) +\n  geom_point(alpha = 0.5, color = \"darkblue\") +\n  geom_smooth(method = \"lm\", color = \"red\") +\n  labs(title = \"Relationship Between PM2.5 Concentration and Air Quality Index (AQI)\",\n       x = \"PM2.5 Concentration\",\n       y = \"Air Quality Index\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](blog-3_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n1.  Scatter plot of PM2.5 vs AQI value This scatter plot shows the relationship between the daily average concentration of PM2.5 (X-axis) and the corresponding Air Quality Index (AQI) value (Y-axis). Each blue dot represents a day's measurement. The red line is a linear regression line showing the overall trend. The strong positive correlation visible in this graph shows that as PM2.5 concentrations increase, AQI values also increase in a predictable manner. This relationship is to be expected, as PM2.5 is the main component in calculating AQI values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Bar chart of PM2.5 by month (seasonal patterns)\nhead(epa_data$Date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1/1/2020\"  \"1/4/2020\"  \"1/7/2020\"  \"1/10/2020\" \"1/13/2020\" \"1/16/2020\"\n```\n\n\n:::\n\n```{.r .cell-code}\nepa_data$Date <- as.Date(epa_data$Date)\n \nepa_data$Month <- as.numeric(format(epa_data$Date, \"%m\"))\n \nmonthly_avg <- epa_data |>\n  group_by(Month) |>\n  summarize(avg_pm25 = mean(`Daily Mean PM2.5 Concentration`, na.rm = TRUE))\n \nggplot(monthly_avg, aes(x = factor(Month), y = avg_pm25)) +\n  geom_bar(stat = \"identity\", fill = \"darkgreen\") +\n  labs(title = \"Monthly Variation in PM2.5 Concentration\",\n       x = \"Month\",\n       y = \"Average PM2.5 Concentration\") +\n  scale_x_discrete(labels = month.abb) \n```\n\n::: {.cell-output-display}\n![](blog-3_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n2.  Bar chart of PM2.5 by month (seasonal patterns) This bar chart shows the average PM2.5 concentration for each month of the year. The X-axis shows the month and the Y-axis shows the average concentration of PM2.5. This visualization reveals seasonal patterns of air pollution. You can see which months typically have higher or lower PM2.5 levels. Typically, the winter months show higher concentrations due to increased heating and temperature inversions of trapped pollutants, while the summer months may have lower concentrations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. Bar chart of observation count by monitoring method\nmethod_counts <- epa_data |>\n  group_by(`Method Description`) |>\n  summarize(count = n()) |>\n  arrange(desc(count))\n\nggplot(head(method_counts, 10), aes(x = reorder(`Method Description`, count), y = count)) +\n  geom_bar(stat = \"identity\", fill = \"purple\") +\n  coord_flip() +\n  labs(title = \"Frequency of Monitoring Methods (Top 10)\",\n       x = \"Monitoring Method\",\n       y = \"Number of Observations\") \n```\n\n::: {.cell-output-display}\n![](blog-3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n3.  Bar chart of observation count by monitoring method This bar chart shows the ten most commonly used methods for monitoring PM2.5 concentrations. The Y-axis lists the different monitoring method descriptions, and the X-axis shows the count of observations made using each method. This visualization is important for understanding data collection methods. Different monitoring methods may have different levels of accuracy, detection limits, or biases. Datasets dominated by one or both methods provide more consistent measurements, while more diverse method sets may introduce variability that needs to be taken into account when interpreting results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepa_data <- readRDS(\"dataset/air_qual_clean.rds\")\n\ndiscrete_vars <- sapply(epa_data, function(x) is.factor(x) || is.character(x) || is.logical(x))\ndiscrete_data <- epa_data[, discrete_vars]\n\nggplot(epa_data, aes(x = `Local Site Name`)) +\n  geom_bar(fill = \"steelblue\") +\n  labs(title = \"Distribution of Air Quality Event Types\",\n       x = \"Local Site Name\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](blog-3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "blog-3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}